# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          pm2 stop sales
          rm sales -R
          git clone https://${{ secrets.GIT_USER}}:${{ secrets.GIT_token }}@github.com/TippieCodes/tippie.me-sales/
          cp tippie.me-sales/back-end sales -R
          rm /var/www/tippie.me/public_html/sales -rf
          cp tippie.me-sales/front-end /var/www/tippie.me/public_html/sales  -R
          echo "let vars = {'websocket_url': 'wss://tippie.me/sales','root_url': '/sales/','api': 'https://tippie.me/sales/api','auth_url': 'https://tippie.me/auth.html'}" > /var/www/tippie.me/public_html/sales/src/vars.js 
          rm tippie.me-sales -rf
          cd sales
          echo -e "GLOBAL_DB=sales-global\nDB_HOST=localhost\nDB_USER=${{secrets.DB_PRODUCTION_USER}}\nDB_PASS=${{ secrets.DB_PRODUCTION_PASSW }}\nAPI_PORT=3001\nWS_PORT=3000\nAPI_ALLOWED_ORIGINS=shops\.schoolrp\.net$" > .env
          npm install --loglevel verbose
          pm2 start sales.js --name sales
          pm2 save
  

